server:
  servlet:
    context-path: /api/v1
spring:
  config:
    import:
      - file:.env[.properties]

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/sprnt_db
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: my-app-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  flyway:
    enabled: true
    baseline-version: 1.1
    # baseline-on-migrate: true

app:
  base-url: http://localhost:8080/api/
  client-url: http://localhost:3000/auth/activate

jwt:
  secret: ${JWT_SECRET}
