server:
  servlet:
    context-path: /api/v1
spring:
  config:
    import:
      - file:.env[.properties]

  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/sprnt_db
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
